### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by DotRacel** [rochus-keller/LjTools#3]
Can't find the target file in luajit called "luajit.pri"

**Comment by rochus-keller** [comment]
You can use this version of LuaJIT: https://github.com/rochus-keller/LuaJIT/tree/LjTools
in case you want to directly integrate the LuaJIT source files. Don't forget to first run the LuaJIT make file one time so the platform specific files are generated which luajit.pri expects. You also have to adjust the path of the include() statement in the pro file.

If you have a pre-existing LuaJIT 2.0 installation you can use that one and set the INCLUDEPATH and LIBS variables accordingly in the pro file.

Are you on Linux or Windows?

**Comment by DotRacel** [comment]
Linux

**Comment by DotRacel** [comment]
You have discord or sth?

**Comment by rochus-keller** [comment]
I have email, see the address provided at https://github.com/rochus-keller (me at rochus-keller dot ch).

**Comment by DotRacel** [comment]
so im using linux to build it. anything i should pay attention ?

**Comment by rochus-keller** [comment]
I updated the readme and added binary versions for LjAsmEditor and LjBcViewer for Linux i386. Maybe you can use them. Otherwise just follow the build steps described in the readme.
