### ISSUE TITLE
Is it possible to disassembler this kind of luajit file?

### ISSUE THREAD

**Issue by DotRacel** [rochus-keller/LjTools#4]
[hello_world.zip](https://github.com/rochus-keller/LjTools/files/4447707/hello_world.zip)

[luajit.zip](https://github.com/rochus-keller/LjTools/files/4447708/luajit.zip)

hello_world is compiled with the luajit.
lua script file can be compiled with the luajit with command "./luajit.exe -b in.lua out.**"

**Comment by rochus-keller** [comment]
Your LuaJIT bytecode file in hello_world.zip was apparently created with the 2.1 beta version of LuaJIT. LjTools only supports the current official release LuaJIT 2.0. You can print the version using the command "luajit -v".

**Comment by DotRacel** [comment]
will you support it

**Comment by rochus-keller** [comment]
It's low priority on my list. Fully satisfied with LJ 2.0. What do you need from LJ 2.1 which is not already available in 2.0?

**Comment by DotRacel** [comment]
a game is using it so..

**Comment by rochus-keller** [comment]
I see. But do you really intend to write LuaJIT assembler, or is it just about disassembling or decompiling? If the latter then there are already tools you can use.

**Comment by DotRacel** [comment]
i want the assembler/disassembler.
there're some decompilers as far as a know
but there's no assembler/disassembler which looks like LjTools

**Comment by rochus-keller** [comment]
Ok, I see. Unfortunately I cannot offer a short term solution. Maybe you could compile the sources with LuaJIT 2.0 instead of 2.1 so you could make use of the current LjTools version.

**Comment by DotRacel** [comment]
For the decompilers, do you have recommends?

**Comment by rochus-keller** [comment]
I only used the built-in disassembler features of LuaJIT, not a decompiler (i.e. LuaJIT bytecode to Lua source code translator). But people don't seem to properly differentiate between disassembler and decompiler. If you google for "luajit decompiler" you get many hits of projects which are apparently disassemblers, not decompilers.
