### ISSUE TITLE
loading bytecode dump text file

### ISSUE THREAD

**Issue by Fedora7** [rochus-keller/LjTools#5]
If I edited the bytecode dump text (add, deleted or modified lines or values) while still keep it in the format as defined in http://wiki.luajit.org/Bytecode-2.0#luajit-2-0-bytecode-dump-format, can this tool or some of the internal functions help to load the dump text back to program via parser and then save to a new binary bytecode file ? Thanks

**Comment by rochus-keller** [comment]
> can this tool or some of the internal functions help to load the dump text back to program via parser and then save to a new binary bytecode file ? 

No, I'm using my own bytecode assembler which is defined here: http://software.rochus-keller.info/LjAsm_Syntax.pdf. And I didn't use it for some time now since my compiler front-ends now all directly generate binary bytecode files.

**Comment by Fedora7** [comment]
Thanks for the info. Do you happen to know any parser in other projects can read the luajit bytecode dump format and convert it back to bytecode ?

**Comment by rochus-keller** [comment]
> Do you happen to know any parser in other projects can read the luajit bytecode dump format

No, but I didn't do much research; but such a parser would probably be built quickly.
